spring:
  application:
    name: api
  redis:
    host: localhost
    password: sc_admin
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: hgxljl
#    key-store-type: PKCS12
#    key-alias: tomcat