spring:
  application:
    name: api
  redis:
    host: localhost
    password: sc_admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true
#zuul:
#  ribbon:
#    eager-load:
#      enabled: true
#ribbon:
#  eager-load:
#    enabled: true
#    clients: user, activity, audit, message
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: hgxljl
#    key-store-type: PKCS12
#    key-alias: tomcat